CREATE TABLE IF NOT EXISTS servers (
	guildID INTEGER NOT NULL,
	guildName TEXT,
	PRIMARY KEY (guildID)
);

CREATE TABLE NOT EXISTS roles (
	roleID INTEGER NOT NULL,
	guildID INTEGER NOT NULL,
	roleType INTEGER,
	roleType INTEGER,
	roleRegex TEXT,
	PRIMARY KEY (roleID, guildID),
	FOREIGN KEY (guildID) REFERENCES server (guildID)
		ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE NOT EXISTS users (
	userID INTEGER NOT NULL,
	guildID INTEGER NOT NULL,
	xp INTEGER,
	userLevel INTEGER,
	PRIMARY KEY (userID, guildID),
	FOREIGN KEY (guildID) REFERENCES server (guildID)
		ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE NOT EXISTS modpacks (
    packName TEXT NOT NULL,
    game TEXT,
    guildID INTEGER NOT NULL,
    packLink TEXT NOT NULL,
    PRIMARY KEY (packName, guildID),
    FOREIGN KEY (guildID) REFERENCES server (guildID)
        ON DELETE CASCADE ON UPDATE NO ACTION
)